AllCops:
  Exclude:
  - 'test/**/*'
  - 'node_modules/**/*'
  - 'config/**/*'
  - 'bin/**/*'
  - 'Gemfile'
  - 'db/seeds.rb'
  - 'db/schema.rb'
Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100